# Generated by Django 2.2 on 2020-08-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Эл. почта'),
        ),
    ]
