# Generated by Django 2.2 on 2020-08-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200801_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=15, verbose_name='Статус'),
        ),
    ]
